language: ruby

dist: focal

branches:
  only:
  - master

cache: bundler

addons:
  postgresql: "12.8"
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12

services:
  - postgresql
    
env:
  global:
  - PGPORT=5433
  - PGUSER=travis

before_install:
  - gem install bundler -v '~> 2.2.27'

before_script:
  - cp config/tess.example.yml config/tess.yml
  - cp config/secrets.travis.yml config/secrets.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rake db:setup
  
after_success:
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r report.xml
