defaults: &defaults
  google_analytics_code: <%= ENV["GOOGLE_ANALYTICS_CODE"] %>
  google_maps_api_key: <%= ENV["GOOGLE_MAPS_API_KEY"] %>
  recaptcha:
    sitekey: <%= ENV["RECAPTCHA_SITEKEY"] %>
    secret: <%= ENV["RECAPTCHA_SECRET"] %>
  elixir_aai:
    client_id: <%= ENV["AAI_CLIENT_ID"] %>
    secret: <%= ENV["AAI_SECRET"] %>
  oidc:
    label:             # service label
    client_id:         # client id
    secret:            # secret
    redirect_uri:      # redirect_uri e.g. https://<host address>/users/auth/oidc/callback
    issuer:            # issuer uri e.g. https://central.test.aaf.edu.au
    host:              # host e.g. central.text.aaf.edu.au
  oidc2:
    label:             # service label
    client_id:         # client id
    secret:            # secret
    redirect_uri:      # redirect_uri e.g. https://<host address>/users/auth/oidc/callback
    issuer:            # issuer uri e.g. https://openidconnect.test.tuakiri.ac.nz
    host:              # host e.g. central.text.aaf.edu.au
  bioportal_api_key: <%= ENV["BIOPORTAL_API_KEY"] %>
  biosharing_api_key: <%= ENV["BIOSHARING_API_KEY"] %>
  fairsharing_api_key: <%= ENV["FAIRSHARING_API_KEY
  secret_key_base: <%= ENV["SECRET_BASE_KEY"] %>
  database:
    :host: <%= ENV["DB_HOST"] %>
    :name: <%= ENV["DB_NAME"] %>
    :username: <%= ENV["DB_USER"] %>
    :password: <%= ENV["DB_PASSWORD"] %>

#Internal config
development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
