default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= Rails.application.secrets[:database][:username] %>
  password: <%= Rails.application.secrets[:database][:password] %>
  host: <%= ENV["DB_HOST"] %>

development:
  <<: *default
  database: <%= Rails.application.secrets[:database][:name] %>_development

test:
  <<: *default
  database: <%= Rails.application.secrets[:database][:name] %>_test

production:
  <<: *default
  database: <%= Rails.application.secrets[:database][:name] %>_production
