default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= Rails.application.secrets[:database][:username] %>
  password: <%= Rails.application.secrets[:database][:password] %>
  host: <%= Rails.application.secrets[:database][:host] %>

development:
  <<: *default
  database: <%= Rails.application.secrets[:database][:name] %>_development

test:
  <<: *default
  database: <%= Rails.application.secrets[:database][:name] %>_test

production:
  <<: *default
  database: <%= Rails.application.secrets[:database][:name] %>_production
