default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { Rails.application.secrets[:database][:host] } %>
  database: <%= ENV.fetch("DB_NAME") { Rails.application.secrets[:database][:name] } %>
  username: <%= ENV.fetch("DB_USER") { Rails.application.secrets[:database][:username] } %>
  password: <%= ENV.fetch("DB_PASSWORD") { Rails.application.secrets[:database][:password] } %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
