# All values will be pulled from the .env file
defaults: &defaults
  secret_key_base: <%= ENV["SECRET_BASE_KEY"] %>
  database:
    :host: <%= ENV["DB_HOST"] %>
    :name: <%= ENV["DB_NAME"] %>
    :username: <%= ENV["DB_USER"] %>
    :password: <%= ENV["DB_PASSWORD"] %>
  recaptcha:
    sitekey: <%= ENV["RECAPTCHA_SITEKEY"] %>
    secret: <%= ENV["RECAPTCHA_SECRET"] %>
  elixir_aai:
    client_id: <%= ENV["AAI_CLIENT_ID"] %>
    secret: <%= ENV["AAI_SECRET"] %>
  google_maps_api_key: <%= ENV["GOOGLE_MAPS_API_KEY"] %>
  google_analytics_code: <%= ENV["GOOGLE_ANALYTICS_CODE"] %>
  bioportal_api_key: <%= ENV["BIOPORTAL_API_KEY"] %>
  biosharing_api_key: <%= ENV["BIOSHARING_API_KEY"] %>
  fairsharing_api_key: <%= ENV["FAIRSHARING_API_KEY"] %>

#Internal config
development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
