config: &config
  secret_key_base: test_key
  database:
    :name: tess
    :username: tess
    :password: password
    :host: localhost
  google_analytics_code:
  google_maps_api_key:
  recaptcha:
    sitekey:
    secret:
  elixir_aai:
    client_id: # client id
    secret: # secret
  oidc:
    label:             # service label
    client_id:         # client id
    secret:            # secret
    redirect_uri:      # redirect_uri e.g. https://<host address>/users/auth/oidc/callback
    issuer:            # issuer uri e.g. https://central.test.aaf.edu.au
    host:              # host e.g. central.text.aaf.edu.au
  oidc2:
    label:             # service label
    client_id:         # client id
    secret:            # secret
    redirect_uri:      # redirect_uri e.g. https://<host address>/users/auth/oidc/callback
    issuer:            # issuer uri e.g. https://openidconnect.test.tuakiri.ac.nz
    host:              # host e.g. central.text.aaf.edu.au
  bioportal_api_key:

production:
  <<: *config

test:
  <<: *config
