# All values will be pulled from the .env file
defaults: &defaults
  secret_key_base: <%= ENV["SECRET_BASE_KEY"] %>
  database:
    :host: <%= ENV["DB_HOST"] %>
    :name: <%= ENV["DB_NAME"] %>
    :username: <%= ENV["DB_USER"] %>
    :password: <%= ENV["DB_PASSWORD"] %>
  recaptcha:
    sitekey:
    secret:
  elixir_aai:
    client_id: #client
    secret: #secret
  google_maps_api_key:
  google_analytics_code:
  bioportal_api_key:
  biosharing_api_key:
  fairsharing_api_key: 7f1af03ac7aec02b572656550f37d2f1e8f77b7b

#Internal config
development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
