production:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/tess_production

development:
  solr:
    hostname: localhost
    port: 8983
    log_level: INFO
    path: /solr/tess_development

test:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/tess_test