production:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/default
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO
    path: /solr/development

test:
  solr:
    url: http://<%= Rails.application.secrets[:solr][:username] %>:<%= Rails.application.secrets[:solr][:password] %>@tess.oerc.ox.ac.uk
    port: 8080
    log_level: WARNING
    path: /solr
