default: &default
  base_url: http://localhost:3000
  contact_email: contact@example.com
  solr_enabled: true
  announcement_message:
  prevent_robot_indexing: false

development:
  <<: *default

production:
  <<: *default

test:
  <<: *default
