default: &default
  base_url: http://localhost:3000
  contact_email: contact@example.com
  sender_email: no-reply@localhost
  solr_enabled: true
  announcement_message:
  prevent_robot_indexing: false
  blocked_domains:
    - !ruby/regexp '/bad-domain\.example/'
  site:
    title: ''
    favicon: ''
    logo: ''
    logo_alt: ''
    theme: 'en'
  questionnaire:
    show: false
    message: ''
    url: ''
  parent_org:
    name: ''
    url: ''
  feature:
    e-learnings: true
    events: true
    materials: true
    nodes: true
    providers: true
    workflows: true

elixir: &elixir
  site:
    title: 'TeSS (Training eSupport System)'
    favicon: favicon.png
    logo: ELIXIR_TeSS_logo_white-80px-height.png
    logo_alt: 'Training eSupport System'
    theme: 'en-EU'
  questionnaire:
    show: true
    message: 'Help TeSS by giving us your feedback:'
    url: 'https://goo.gl/forms/jsVC70q6oN8FsGWR2'
  parent_org:
    name: 'ELIXIR Hub'
    image: hub-logo.png
    url: 'http://www.elixir-europe.org'

atrac: &atrac
  site:
    title: 'ATRaC (Develop)'
    favicon: atrac-logo.ico
    logo: atrac-logo.png
    logo_alt: 'ATRaC Home'
    theme: 'en-AU'
  feature:
    e-learnings: false
    events: true
    materials: true
    nodes: false
    providers: true
    workflows: false

development:
  <<: *default
  <<: *elixir

production:
  <<: *default
  <<: *elixir

test:
  <<: *default
