default: &default
  base_url: http://localhost:3000
  contact_email: contact@example.com
  sender_email: no-reply@localhost
  solr_enabled: true
  announcement_message:
  prevent_robot_indexing: false
  blocked_domains:
    - !ruby/regexp '/bad-domain\.example/'
  site:
    title: ''
    title_short: ''
    favicon: ''
    logo: ''
    logo_alt: ''
    theme: 'en'
    repository: ''
    supported_by: ''
    widget_example: ''
    gmaps_api_key: ''
    registrations: true
  questionnaire:
    show: false
    message: ''
    url: ''
  parent_org:
    name: ''
    url: ''
  feature:
    e-learnings: true
    events: true
    materials: true
    nodes: true
    packages: true
    providers: true
    workflows: true
    disabled: []
  dictionaries:
    difficulty: 'difficulty.yml'
    eligibility: 'eligibility.yml'
    event_types: 'event_types.yml'
    cost_basis: 'cost_basis.yml'

elixir: &elixir
  site:
    title: 'TeSS (Training eSupport System)'
    title_short: TeSS
    favicon: favicon.png
    logo: ELIXIR_TeSS_logo_white-80px-height.png
    logo_alt: 'Training eSupport System'
    theme: 'en-EU'
    repository: 'https://github.com/ElixirTeSS/TeSS'
    supported_by: 'elixir_supported_by'
    widget_example: 'elixir_widget_example'
    gmaps_api_key: ''
  questionnaire:
    show: true
    message: 'Help TeSS by giving us your feedback:'
    url: 'https://goo.gl/forms/jsVC70q6oN8FsGWR2'
  parent_org:
    name: 'ELIXIR Hub'
    image: hub-logo.png
    url: 'http://www.elixir-europe.org'

dresa: &dresa
  site:
    title: 'Digital Research Skills Australia (DReSA)'
    title_short: 'DReSA'
    favicon: atrac-logo.ico
    logo: atrac-logo.png
    logo_alt: 'Digital Research Skills Australasia'
    theme: 'en-AU'
    repository: 'https://github.com/nrmay/TeSS'
    supported_by: 'dresa_supported_by.erb'
    widget_example: 'elixir_widget_example'
    gmaps_api_key: ''
    registration: false
  feature:
    e-learnings: false
    events: true
    materials: true
    nodes: false
    packages: false
    providers: true
    workflows: false
    disabled: ['county', 'operations', 'sponsors', 'materials']
  dictionaries:
    difficulty: 'difficulty_dresa.yml'
    eligibility: 'eligibility_dresa.yml'
    event_types: 'event_types_dresa.yml'
    cost_basis: 'cost_basis.yml'

development:
  <<: *default

production:
  <<: *default

test:
  <<: *default
