default: &default
  base_url: http://localhost:3000
  contact_email: contact@example.com
  sender_email: no-reply@localhost
  solr_enabled: true
  announcement_message:
  prevent_robot_indexing: false
  blocked_domains:
    - !ruby/regexp '/bad-domain\.example/'

development:
  <<: *default

production:
  <<: *default

test:
  <<: *default
