default: &default
  base_url: <%= ENV.fetch("BASE_URL") %>
  contact_email: <%= ENV.fetch("CONTACT_EMAIL") %>
  sender_email: <%= ENV.fetch("SENDER_EMAIL") %>
  solr_enabled: true
  announcement_message:
  prevent_robot_indexing: false
  blocked_domains:
    - !ruby/regexp '/bad-domain\.example/'
  feature:
    events: true
    materials: true
    e-learning: false
    workflows: false
    collections: false
    providers: false
    about: true


development:
  <<: *default

production:
  <<: *default

test:
  <<: *default
