default: &default
  base_url: <%= ENV("BASE_URL") %>
  contact_email: <%= ENV("CONTACT_EMAIL") %>
  sender_email: <%= ENV("SENDER_EMAIL") %>
  solr_enabled: true
  announcement_message:
  prevent_robot_indexing: false
  blocked_domains:
    - !ruby/regexp '/bad-domain\.example/'

development:
  <<: *default

production:
  <<: *default

test:
  <<: *default
