webinar:
  title: Webinars
workshop:
  title: Workshops and courses
conference:
  title: Conferences
cop_meeting:
  title: CoP Meetings
hackathon:
  title: Hackathons
dropin:
  title: Drop-in sessions and hackyhours
