# Subset of iso-639-1 (2 letter codes), 24 official EU languages
# See: https://id.loc.gov/vocabulary/iso639-1.html
# See config/locales for how these languages are rendered
---
en:
  title: 'English'
  uri: http://id.loc.gov/vocabulary/iso639-1/en
fr:
  title: 'French'
  uri: http://id.loc.gov/vocabulary/iso639-1/fr
de:
  title: 'German'
  uri: http://id.loc.gov/vocabulary/iso639-1/de
es:
  title: 'Spanish'
  uri: http://id.loc.gov/vocabulary/iso639-1/es
nl:
  title: 'Dutch'
  uri: http://id.loc.gov/vocabulary/iso639-1/nl
bg:
  title: 'Bulgarian'
  uri: http://id.loc.gov/vocabulary/iso639-1/bg
hr:
  title: 'Croatian'
  uri: http://id.loc.gov/vocabulary/iso639-1/hr
cs:
  title: 'Czech'
  uri: http://id.loc.gov/vocabulary/iso639-1/cs
da:
  title: 'Danish'
  uri: http://id.loc.gov/vocabulary/iso639-1/da
et:
  title: 'Estonian'
  uri: http://id.loc.gov/vocabulary/iso639-1/et
fi:
  title: 'Finnish'
  uri: http://id.loc.gov/vocabulary/iso639-1/fi
el:
  title: 'Greek'
  uri: http://id.loc.gov/vocabulary/iso639-1/el
hu:
  title: 'Hungarian'
  uri: http://id.loc.gov/vocabulary/iso639-1/hu
ga:
  title: 'Irish'
  uri: http://id.loc.gov/vocabulary/iso639-1/ga
it:
  title: 'Italian'
  uri: http://id.loc.gov/vocabulary/iso639-1/it
lv:
  title: 'Latvian'
  uri: http://id.loc.gov/vocabulary/iso639-1/lv
lt:
  title: 'Lithuanian'
  uri: http://id.loc.gov/vocabulary/iso639-1/lt
mt:
  title: 'Maltese'
  uri: http://id.loc.gov/vocabulary/iso639-1/mt
pl:
  title: 'Polish'
  uri: http://id.loc.gov/vocabulary/iso639-1/pl
pt:
  title: 'Portugeuse'
  uri: http://id.loc.gov/vocabulary/iso639-1/pt
ro:
  title: 'Romanian'
  uri: http://id.loc.gov/vocabulary/iso639-1/ro
sk:
  title: 'Slovak'
  uri: http://id.loc.gov/vocabulary/iso639-1/sk
sl:
  title: 'Slovenian'
  uri: http://id.loc.gov/vocabulary/iso639-1/sl
sv:
  title: 'Swedish'
  uri: http://id.loc.gov/vocabulary/iso639-1/sv
