description:
  webinar:
    title: 'webinar'
  zoom:
    title: 'zoom'
  ms_teams:
    title: 'ms teams'
  online_workshop:
    title: 'online workshop'
venue:
  webinar:
    title: 'webinar'
  zoom:
    title: 'zoom'
  ms_teams:
    title: 'teams'
  online_workshop:
    title: 'online'
