version: 3.8
services:
  tess:
    container_name: tess
    build:
      context: .
      target: development
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - '3000:3000'
  db:
    container_name: postgres
    logging:
      driver: none
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: ${DEVELOPMENT_DB}
      POSTGRES_USER: ${DEVELOPMENT_DB_USER}
      POSTGRES_PASSWORD: ${DEVELOPMENT_DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin4
    logging:
      driver: none
    image: dpage/pgadmin4:latest
    restart: always
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${POSTGRES_USER}@${POSTGRES_USER}.com
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - '8080:80'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  db-data:
  pgadmin-data:
