name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DB_HOST: localhost
      DB_NAME: tess
      DB_USER: tess
      DB_PASSWORD: password
      SECRET_BASE_KEY: test_key
    steps:
      - uses: harmon758/postgresql-action@v1
        with:
          postgresql db: '${DB_NAME}_test'
          postgresql user: ${DB_USER}
          postgresql password: ${DB_PASSWORD}
        name: Set up database

      - uses: actions/checkout@v2
        name: Set up Ruby

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
        name: Bundle install
      - run: bundle exec rake db:test:prepare && bundle exec rake test
        name: Run tests
      - name: Codacy Coverage Reporter
      uses: codacy/codacy-coverage-reporter-action@v1.1.0
      with:
        # API project token to retrieve your remote Codacy configuration for the project being analyzed
        project-token: ${secrets.CODACY_PROJECT_TOKEN}
        api-token: ${secrets.CODACY_API_TOKEN}
